services:
  grafana-minimal:
    image: grafana/grafana:latest
    container_name: grafana-minimal
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro