# https://github.com/sgl-project/sglang/blob/main/examples/monitoring/prometheus.yaml

global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: sglang
    static_configs:
      - targets:
          - sglang:30000