# https://docs.sglang.io/platforms/cpu_server.html#install-using-docker

name: Build and Push Docker (SGLang CPU)

on: workflow_dispatch

permissions:
  contents: write
  packages: write

jobs:
  docker-sglang-cpu:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout SGLang source
        uses: actions/checkout@v6
        with:
          repository: sgl-project/sglang
          ref: main
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push SGLang CPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/xeon.Dockerfile
          push: true
          pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/sglang-cpu:latest
